const travelQuotes = [
        "\"The world is a book and those who do not travel read only one page.\"" + " - \"Saint Augustine\"",
        "\"Not all those who wander are lost.\"" + " - \"J.R.R. Tolkien\"",
        "\"Travel is fatal to prejudice, bigotry, and narrow-mindedness.\"" + " - \"Mark Twain\"",
        "\"The journey not the arrival matters.\"" + " - \"T.S. Eliot\"",
        "\"We travel, some of us forever, to seek other states, other lives, other souls.\"" + " - \"Anaïs Nin\"",
        "\"A journey of a thousand miles begins with a single step.\"" + " - \"Lao Tzu\"",
        "\"Traveling – it leaves you speechless, then turns you into a storyteller.\"" + " - \"Ibn Battuta\"",
        "\"Not until we are lost do we begin to understand ourselves.\"" + " - \"Henry David Thoreau\"",
        "\"I haven't been everywhere, but it's on my list.\"" + " - \"Susan Sontag\"",
        "\"Adventure is worthwhile.\"" + " - \"Aesop\"",
        "\"Once a year, go someplace you've never been before.\"" + " - \"Dalai Lama\"",
        "\"The gladdest moment in human life is a departure into unknown lands.\"" + " - \"Sir Richard Burton\"",
        "\"To awaken alone in a strange town is one of the pleasantest sensations in the world.\"" + " - \"Freya Stark\"",
        "\"I travel not to escape life, but for life not to escape me.\"" + " - \"Anonymous\"",
        "\"To travel is to live.\"" + " - \"Hans Christian Andersen\"",
        "\"I travel light. I think the most important thing is to be in a good mood and enjoy life, wherever you are.\"" + " - \"Diane von Fürstenberg\"",
        "\"The world is too big to stay in one place and life is too short to do just one thing.\"" + " - \"Anonymous\"",
        "\"Investment in travel is an investment in yourself.\"" + " - \"Matthew Karsten\"",
        "\"I travel not to find myself but to rediscover who I've been all along.\"" + " - \"Anonymous\"",
        "\"Travel makes one modest. You see what a tiny place you occupy in the world.\"" + " - \"Gustave Flaubert\"",
        "\"Travel far enough, you meet yourself.\"" + " - \"David Mitchell\"",
        "\"Travel is the only thing you can buy that makes you richer.\"" + " - \"Anonymous\"",
        "\"The best education I have ever received was through travel.\"" + " - \"Lisa Ling\"",
        "\"The world is a book, and those who do not travel read only a page.\"" + " - \"Attributed to Saint Augustine\"",
        "\"Traveling is like flirting with life. It's like saying, 'I would stay and love you, but I have to go; this is my station.'\"" + " - \"Lisa St. Aubin de Terán\"",
        "\"One's destination is never a place, but a new way of seeing things.\"" + " - \"Henry Miller\"",
        "\"Jet lag is for amateurs.\"" + " - \"Dick Clark\"",
        "\"Life is short and the world is wide.\"" + " - \"Simon Raven\"",
        "\"The impulse to travel is one of the hopeful symptoms of life.\"" + " - \"Agnes Repplier\"",
        "\"Travel far enough, you meet yourself.\""+ " - \"Joseph Campbell\"",
        "\"We travel for romance, we travel for architecture, and we travel to be lost.\"" + " - \"Ray Bradbury\"",
        "\"The world is full of wonderful things you haven't seen yet. Don't ever give up on the chance of seeing them.\"" + " - \"J.K. Rowling\"",
        "\"Do not follow where the path may lead. Go instead where there is no path and leave a trail.\"" + " - \"Ralph Waldo Emerson\"",
        "\"Wherever you go becomes a part of you somehow.\"" + " - \"Anita Desai\"",
        "\"A good traveler has no fixed plans and is not intent on arriving.\"" + " - \"Lao Tzu\""
    ]